version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_PASSWD}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_USERNAME}
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - mynetwork
    restart: always
  typesense:
    image: typesense/typesense:27.1
    restart: always
    ports:
      - "8108:8108"
    volumes:
      - typesense:/data
    command: '--data-dir /data --api-key=xyz --enable-cors'

networks:
  mynetwork:
    driver: bridge

volumes:
  mongodb_data:
  typesense:
    driver: local
